version: '3.7'

services: 
    ghpage:
        build:
            context: .
        image: slowmonkey/jekyll-site
        command: "bundle exec jekyll serve --config _config.yml --host 0.0.0.0 --incremental --force_polling"
        volumes:
            - ${PWD}:/srv/jekyll
        ports: 
            - "0.0.0.0:4000:4000"