services: 
    ghpage:
        build:
            context: .
        image: slowmonkey/jekyll-site
        # command: "bundle exec jekyll serve --config _config.yml --host 0.0.0.0 --drafts --incremental --force_polling"
        volumes:
            - ${PWD}:/srv/jekyll
        ports: 
            - 8080:8080